# USERS, ORDERS, ITEMS
SELECT U.USER_ID AS buyer_id, U.JOIN_DATE as join_date, COUNT(O.ORDER_ID) AS orders_in_2019
FROM USERS U
LEFT JOIN ORDERS O ON O.BUYER_ID = U.USER_ID
AND ORDER_DATE LIKE ('2019%')
GROUP BY U.USER_ID, U.JOIN_DATE;